basePath: /
definitions:
  categories.createCategoryInput:
    properties:
      description:
        type: string
      name:
        type: string
      teste:
        type: string
    type: object
  categories.updateCategoryBody:
    properties:
      description:
        type: string
      name:
        type: string
      teste:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gerenciamento de categorias
  title: Categories API
  version: "1.0"
paths:
  /categories:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Listar categorias
      tags:
      - categories
    post:
      consumes:
      - application/json
      parameters:
      - description: Nome da categoria
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/categories.createCategoryInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Criar categoria
      tags:
      - categories
  /categories/{id}:
    delete:
      parameters:
      - description: ID da categoria
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Deletar categoria
      tags:
      - categories
    get:
      parameters:
      - description: ID da categoria
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Buscar categoria por ID
      tags:
      - categories
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID da categoria
        in: path
        name: id
        required: true
        type: integer
      - description: Novo nome
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/categories.updateCategoryBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Atualizar categoria
      tags:
      - categories
swagger: "2.0"
